@extends('app.layout')
@section('title','Kelola Voucher — TBN')
@section('content')
<div class="hero"><div><div class="eyebrow">Pusat Reward Pengelola</div><div class="title">Kelola Voucher 🎟️</div><p class="subtitle">Tambahkan, ubah, aktifkan, atau nonaktifkan kode voucher WiFi dan koperasi.</p></div></div>
<div class="card"><h3>Tambah Voucher</h3><form method="POST" action="{{ route('vouchers.store') }}" class="form-grid">@csrf
<div class="field"><label>Nama voucher</label><input name="name" required placeholder="Voucher WiFi 2 Jam"></div><div class="field"><label>Jenis</label><select name="type"><option value="wifi">WiFi</option><option value="koperasi">Koperasi</option></select></div>
<div class="field"><label>Kode voucher</label><input name="code" required placeholder="WIFI-TBN-2026"></div><div class="field"><label>Biaya poin</label><input name="points_cost" type="number" min="1" required value="50"></div>
<div class="field"><label>Stok</label><input name="stock" type="number" min="0" required value="10"></div><div class="field"><label>Kedaluwarsa (opsional)</label><input name="expires_at" type="datetime-local"></div>
<div class="field full"><label>Deskripsi</label><input name="description" placeholder="Keterangan voucher"></div><div class="field full"><label><input type="checkbox" name="is_active" value="1" checked> Aktif</label></div><div class="field full"><button class="btn btn-primary" type="submit">+ Tambah Voucher</button></div></form></div>
<div class="card" style="margin-top:18px"><h3>Daftar Voucher</h3><div class="table-wrap"><table class="table"><thead><tr><th>Nama</th><th>Jenis</th><th>Kode</th><th>Poin</th><th>Stok</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
@forelse($vouchers as $v)<tr><td><b>{{ $v->name }}</b><br><small>{{ $v->description }}</small></td><td>{{ $v->typeLabel }}</td><td><code>{{ $v->code }}</code></td><td>{{ number_format($v->points_cost) }}</td><td>{{ $v->stock }}</td><td><span class="status">{{ $v->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td><details><summary class="btn btn-light" style="cursor:pointer">Edit</summary><form method="POST" action="{{ route('vouchers.update',$v) }}" class="form-grid" style="margin-top:10px">@csrf @method('PUT')<div class="field"><label>Nama</label><input name="name" value="{{ $v->name }}" required></div><div class="field"><label>Jenis</label><select name="type"><option value="wifi" @selected($v->type==='wifi')>WiFi</option><option value="koperasi" @selected($v->type==='koperasi')>Koperasi</option></select></div><div class="field"><label>Kode</label><input name="code" value="{{ $v->code }}" required></div><div class="field"><label>Poin</label><input name="points_cost" type="number" min="1" value="{{ $v->points_cost }}" required></div><div class="field"><label>Stok</label><input name="stock" type="number" min="0" value="{{ $v->stock }}" required></div><div class="field"><label>Kedaluwarsa</label><input name="expires_at" type="datetime-local" value="{{ $v->expires_at?->format('Y-m-d\\TH:i') }}"></div><div class="field full"><label>Deskripsi</label><input name="description" value="{{ $v->description }}"></div><div class="field full"><label><input type="checkbox" name="is_active" value="1" @checked($v->is_active)> Aktif</label></div><div class="field full"><button class="btn btn-primary">Simpan Perubahan</button></div></form></details><form method="POST" action="{{ route('vouchers.destroy',$v) }}" style="display:inline" onsubmit="return confirm('Nonaktifkan/hapus voucher ini?')">@csrf @method('DELETE')<button class="btn btn-light" type="submit">Hapus</button></form></td></tr>@empty<tr><td colspan="7">Belum ada voucher.</td></tr>@endforelse
</tbody></table></div></div>
@endsection
