<?php $__env->startSection('title','Poin & Voucher — TBN'); ?>
<?php $__env->startSection('content'); ?>
<div class="hero"><div><div class="eyebrow">Reward Center</div><div class="title">Poin & Voucher 🎁</div><p class="subtitle">Setiap foto sampah yang berhasil dikirim memberikan <b>10 poin</b>.</p></div><span class="points-chip" style="font-size:14px">⭐ <?php echo e(number_format($user->points)); ?> Poin</span></div>
<div class="grid grid-2">
<div class="card"><h3>Voucher Tersedia</h3><p class="subtitle">Tukar poin dengan voucher WiFi atau koperasi.</p><div class="quick-links">
<?php $__empty_1 = true; $__currentLoopData = $vouchers; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $v): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
<div class="quick-link"><span><?php echo e($v->type === 'wifi' ? '📶' : '🛒'); ?></span><div><b><?php echo e($v->name); ?></b><small><?php echo e($v->description ?: 'Voucher TBN'); ?> • Stok <?php echo e($v->stock); ?></small><small><b><?php echo e(number_format($v->points_cost)); ?> poin</b><?php if($v->expires_at): ?> • sampai <?php echo e($v->expires_at->format('d/m/Y')); ?><?php endif; ?></small></div><form method="POST" action="<?php echo e(route('points.redeem',$v)); ?>"><?php echo csrf_field(); ?><button class="btn btn-primary" type="submit" onclick="return confirm('Tukar voucher ini dengan <?php echo e(number_format($v->points_cost)); ?> poin?')">Tukar</button></form></div>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="small-note">Belum ada voucher aktif.</div><?php endif; ?>
</div></div>
<div class="card"><h3>Riwayat Poin</h3><div class="table-wrap"><table class="table"><thead><tr><th>Aktivitas</th><th>Poin</th><th>Saldo</th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $history; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $h): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><?php echo e($h->description); ?></td><td><b style="color:<?php echo e($h->points >= 0 ? '#059669':'#dc2626'); ?>"><?php echo e($h->points >= 0 ? '+' : ''); ?><?php echo e($h->points); ?></b></td><td><?php echo e($h->balance_after); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="3">Belum ada aktivitas poin.</td></tr><?php endif; ?></tbody></table></div></div>
</div>
<div class="card" style="margin-top:18px"><h3>Voucher yang Pernah Ditukar</h3><div class="table-wrap"><table class="table"><thead><tr><th>Voucher</th><th>Kode</th><th>Poin</th><th>Tanggal</th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $redemptions; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $r): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><?php echo e($r->voucher->name ?? 'Voucher'); ?></td><td><b><?php echo e($r->voucher_code); ?></b></td><td><?php echo e(number_format($r->points_spent)); ?></td><td><?php echo e($r->redeemed_at?->format('d M Y H:i')); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="4">Belum ada penukaran.</td></tr><?php endif; ?></tbody></table></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('app.layout', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\xampp-portable-windows-x64-8.2.12-0-VS16\xampp\TBN\resources\views/app/points.blade.php ENDPATH**/ ?>