<?php $__env->startSection('title','Kelola Voucher — TBN'); ?>
<?php $__env->startSection('content'); ?>
<div class="hero"><div><div class="eyebrow">Pusat Reward Pengelola</div><div class="title">Kelola Voucher 🎟️</div><p class="subtitle">Tambahkan, ubah, aktifkan, atau nonaktifkan kode voucher WiFi dan koperasi.</p></div></div>
<div class="card"><h3>Tambah Voucher</h3><form method="POST" action="<?php echo e(route('vouchers.store')); ?>" class="form-grid"><?php echo csrf_field(); ?>
<div class="field"><label>Nama voucher</label><input name="name" required placeholder="Voucher WiFi 2 Jam"></div><div class="field"><label>Jenis</label><select name="type"><option value="wifi">WiFi</option><option value="koperasi">Koperasi</option></select></div>
<div class="field"><label>Kode voucher</label><input name="code" required placeholder="WIFI-TBN-2026"></div><div class="field"><label>Biaya poin</label><input name="points_cost" type="number" min="1" required value="50"></div>
<div class="field"><label>Stok</label><input name="stock" type="number" min="0" required value="10"></div><div class="field"><label>Kedaluwarsa (opsional)</label><input name="expires_at" type="datetime-local"></div>
<div class="field full"><label>Deskripsi</label><input name="description" placeholder="Keterangan voucher"></div><div class="field full"><label><input type="checkbox" name="is_active" value="1" checked> Aktif</label></div><div class="field full"><button class="btn btn-primary" type="submit">+ Tambah Voucher</button></div></form></div>
<div class="card" style="margin-top:18px"><h3>Daftar Voucher</h3><div class="table-wrap"><table class="table"><thead><tr><th>Nama</th><th>Jenis</th><th>Kode</th><th>Poin</th><th>Stok</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $vouchers; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $v): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><b><?php echo e($v->name); ?></b><br><small><?php echo e($v->description); ?></small></td><td><?php echo e($v->typeLabel); ?></td><td><code><?php echo e($v->code); ?></code></td><td><?php echo e(number_format($v->points_cost)); ?></td><td><?php echo e($v->stock); ?></td><td><span class="status"><?php echo e($v->is_active ? 'Aktif' : 'Nonaktif'); ?></span></td><td><details><summary class="btn btn-light" style="cursor:pointer">Edit</summary><form method="POST" action="<?php echo e(route('vouchers.update',$v)); ?>" class="form-grid" style="margin-top:10px"><?php echo csrf_field(); ?> <?php echo method_field('PUT'); ?><div class="field"><label>Nama</label><input name="name" value="<?php echo e($v->name); ?>" required></div><div class="field"><label>Jenis</label><select name="type"><option value="wifi" <?php if($v->type==='wifi'): echo 'selected'; endif; ?>>WiFi</option><option value="koperasi" <?php if($v->type==='koperasi'): echo 'selected'; endif; ?>>Koperasi</option></select></div><div class="field"><label>Kode</label><input name="code" value="<?php echo e($v->code); ?>" required></div><div class="field"><label>Poin</label><input name="points_cost" type="number" min="1" value="<?php echo e($v->points_cost); ?>" required></div><div class="field"><label>Stok</label><input name="stock" type="number" min="0" value="<?php echo e($v->stock); ?>" required></div><div class="field"><label>Kedaluwarsa</label><input name="expires_at" type="datetime-local" value="<?php echo e($v->expires_at?->format('Y-m-d\\TH:i')); ?>"></div><div class="field full"><label>Deskripsi</label><input name="description" value="<?php echo e($v->description); ?>"></div><div class="field full"><label><input type="checkbox" name="is_active" value="1" <?php if($v->is_active): echo 'checked'; endif; ?>> Aktif</label></div><div class="field full"><button class="btn btn-primary">Simpan Perubahan</button></div></form></details><form method="POST" action="<?php echo e(route('vouchers.destroy',$v)); ?>" style="display:inline" onsubmit="return confirm('Nonaktifkan/hapus voucher ini?')"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn btn-light" type="submit">Hapus</button></form></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7">Belum ada voucher.</td></tr><?php endif; ?>
</tbody></table></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('app.layout', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\xampp-portable-windows-x64-8.2.12-0-VS16\xampp\TBN\resources\views/app/vouchers.blade.php ENDPATH**/ ?>